# Generated by Django 5.2.1 on 2025-05-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFerremax', '0002_auto_cargar_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='sincorreo@ejemplo.com', max_length=100, unique=True),
        ),
    ]
