# Generated by Django 5.2.1 on 2025-05-31 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFerremax', '0003_cliente_correo'),
        ('appFerremax', '0004_recargar_comunas_cargos'),
    ]

    operations = [
    ]
