# Generated by Django 5.2.1 on 2025-06-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFerremax', '0006_cargar_empleados'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(default='tempora11234', max_length=100),
            preserve_default=False,
        ),
    ]
