# Generated by Django 5.2.1 on 2025-06-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFerremax', '0007_cliente_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
