# Generated by Django 5.2.1 on 2025-07-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFerremax', '0010_pedido_paypal_payment_id_pedido_total_and_more'),
    ]

    operations = [
    ]
